services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
